### ISSUE TITLE
Can the runtime client still be the old net/rpc client

### ISSUE THREAD

**Issue by bvk** [keegancsmith/rpc#1]
This is a really good fix. Thanks for the package.

It is not clear from the project README, if the rpc mechanism still works between a Server instance using github.com/keegancsmith/rpc package and Client instance using the standard net/rpc package. I haven't looked at the implementation yet, so cloud you please clarify?

**Comment by keegancsmith** [comment]
Yes, there are no changes to the wire protocol so is backwards compatible. Cancellation is communicated via a normal `net/rpc` call (`_goRPC_.Cancel`). I'll update the documentation to make this clearer.
